# Generated by Django 5.1.1 on 2024-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='contenido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
