# Generated by Django 5.1.1 on 2024-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosserviciosproveedor',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
    ]
