# Generated by Django 5.1.1 on 2025-01-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0002_productosserviciosproveedor_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='productos_servicios',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos_servicios',
            field=models.ManyToManyField(to='ProveedoresApp.productosserviciosproveedor', verbose_name='Productos'),
        ),
    ]
