# Generated by Django 5.1.1 on 2025-01-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0003_remove_proveedor_productos_servicios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccionproveedor',
            old_name='estado',
            new_name='provincia',
        ),
    ]
