# Generated by Django 5.1.1 on 2024-10-31 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoriaProducto',
                'verbose_name_plural': 'categoriasProducto',
            },
        ),
        migrations.CreateModel(
            name='FabricanteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fabricanteProducto',
                'verbose_name_plural': 'fabricantesProducto',
            },
        ),
        migrations.CreateModel(
            name='SeccionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'seccionProducto',
                'verbose_name_plural': 'seccionesProducto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda')),
                ('precio', models.FloatField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('sinopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('stock_base', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(default=0)),
                ('limite_stock_maximo', models.IntegerField(default=0)),
                ('cantidad_almacen', models.IntegerField(default=0)),
                ('cantidad_tienda', models.IntegerField(default=0)),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaApp.categoriaproducto')),
                ('fabricante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TiendaApp.fabricanteproducto')),
                ('seccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TiendaApp.seccionproducto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
