# Generated by Django 5.1.1 on 2024-10-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0002_producto_reponer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_almacen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_tienda',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_vendida',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='limite_stock_maximo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_maximo',
        ),
    ]
