# Generated by Django 5.1.1 on 2024-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0003_remove_producto_cantidad_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pedido_reposicion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_en_almacen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_en_tienda',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo_posible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_vendido',
            field=models.IntegerField(default=0),
        ),
    ]
