# Generated by Django 5.1.1 on 2024-10-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0004_producto_pedido_reposicion_producto_stock_en_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_total',
        ),
    ]
