# Generated by Django 5.1.1 on 2024-10-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0005_remove_producto_stock_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(),
        ),
    ]
