# Generated by Django 5.1.1 on 2024-10-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0006_alter_producto_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
    ]
