# Generated by Django 5.1.1 on 2024-11-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0007_remove_producto_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_a_reponer',
            field=models.IntegerField(default=0),
        ),
    ]
