# Generated by Django 5.1.1 on 2024-11-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0008_producto_cantidad_a_reponer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad_a_reponer',
            new_name='cantidad_para_reponer_almacen',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_para_reponer_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
