# Generated by Django 5.1.1 on 2024-11-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0009_rename_cantidad_a_reponer_producto_cantidad_para_reponer_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_para_reponer_almacen',
        ),
    ]
