# Generated by Django 5.1.1 on 2024-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0010_remove_producto_cantidad_para_reponer_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
