# Generated by Django 5.1.1 on 2024-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0011_producto_descuento_producto_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_con_descuento',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_original',
            field=models.FloatField(default=0.0),
        ),
    ]
