# Generated by Django 5.1.1 on 2024-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0012_remove_producto_precio_producto_precio_con_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='beneficios',
            field=models.FloatField(default=0.0),
        ),
    ]
