# Generated by Django 5.1.1 on 2024-11-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0013_producto_beneficios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_con_descuento',
        ),
    ]
