# Generated by Django 5.1.1 on 2024-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0014_remove_producto_precio_con_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0.0),
        ),
    ]
