# Generated by Django 5.1.1 on 2024-11-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0015_alter_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='oferta',
        ),
    ]
