# Generated by Django 5.1.1 on 2024-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0017_alter_producto_precio_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_original',
            field=models.FloatField(default=0.0),
        ),
    ]
