# Generated by Django 5.1.1 on 2024-11-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0019_rename_categorias_producto_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FabricanteProducto',
        ),
    ]
