# Generated by Django 5.1.1 on 2024-11-18 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0001_initial'),
        ('TiendaApp', '0020_delete_fabricanteproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProveedoresApp.proveedor'),
        ),
    ]
