# Generated by Django 5.1.1 on 2024-11-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0002_productosserviciosproveedor_precio'),
        ('TiendaApp', '0023_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_de_proveedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ProveedoresApp.productosserviciosproveedor'),
        ),
    ]
