# Generated by Django 5.1.1 on 2024-11-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0002_productosserviciosproveedor_precio'),
        ('TiendaApp', '0024_producto_precio_de_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_de_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProveedoresApp.productosserviciosproveedor'),
        ),
    ]
