# Generated by Django 5.1.1 on 2024-11-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0002_productosserviciosproveedor_precio'),
        ('TiendaApp', '0025_alter_producto_precio_de_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_dado_por_proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto_nombre', to='ProveedoresApp.productosserviciosproveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_de_proveedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='producto_precio', to='ProveedoresApp.productosserviciosproveedor'),
        ),
    ]
