# Generated by Django 5.1.1 on 2024-11-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0031_alter_producto_nombre_dado_por_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_dado_por_proveedor',
        ),
    ]
