# Generated by Django 5.1.1 on 2024-11-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0032_remove_producto_nombre_dado_por_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_de_proveedor',
        ),
    ]
