# Generated by Django 5.1.1 on 2024-11-19 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0002_productosserviciosproveedor_precio'),
        ('TiendaApp', '0034_producto_nombre_dado_por_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_dado_por_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_nombre', to='ProveedoresApp.productosserviciosproveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_de_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_precio', to='ProveedoresApp.productosserviciosproveedor'),
        ),
    ]
