# Generated by Django 5.1.1 on 2024-11-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0038_alter_producto_nombre_dado_por_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
