# Generated by Django 5.1.1 on 2024-11-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0041_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_maximo_en_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
