# Generated by Django 5.1.1 on 2024-11-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0042_producto_stock_maximo_en_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_original',
            new_name='precio_base',
        ),
    ]
