# Generated by Django 5.1.1 on 2024-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0044_remove_producto_cantidad_para_reponer_tienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_maximo_en_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
