# Generated by Django 5.1.1 on 2024-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0045_producto_stock_maximo_en_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_comprado',
            field=models.IntegerField(default=0),
        ),
    ]
