# Generated by Django 5.1.1 on 2024-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0046_producto_stock_comprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.FloatField(default=21.0),
        ),
    ]
