# Generated by Django 5.1.1 on 2024-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0047_producto_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
    ]
