# Generated by Django 5.1.1 on 2024-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0048_alter_producto_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_total',
            field=models.FloatField(default=0.0),
        ),
    ]
