# Generated by Django 5.1.1 on 2024-12-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0050_producto_correo_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='correo_enviado',
        ),
    ]
